import { iconPairs } from './icons.mjs';

export const templateCopy = iconPairs({
  'Skip to content': 'Ga naar inhoud',
  'Main navigation': 'Hoofdnavigatie',
  'Open navigation': 'Navigatie openen',
  'Close navigation': 'Navigatie sluiten',
  'Find your seat': 'Schuif aan',
  'Come by for coffee': 'Kom langs voor koffie',
  'Enquire about a stay': 'Vraag naar een verblijf',
  'Let’s talk flowers': 'Laten we over bloemen praten',
  'Book a repair': 'Plan een reparatie',
  'Get in touch': 'Neem contact op',
  'Get directions': 'Bekijk de route',
  'Warmly lit restaurant tables with timber chairs and pendant lamps': 'Warm verlichte restauranttafels met houten stoelen en hanglampen',
  'Golden, flaky croissants fresh from the oven': 'Goudbruine, luchtige croissants vers uit de oven',
  'A sunlit hotel bedroom with white linen and natural textures': 'Een zonnige hotelkamer met wit beddengoed en natuurlijke materialen',
  'Buckets of colourful seasonal flowers in a bright flower shop': 'Emmers met kleurrijke seizoensbloemen in een lichte bloemenwinkel',
  'A mechanic working carefully on a bicycle in a workshop': 'Een monteur die zorgvuldig aan een fiets werkt in een werkplaats',
  'Illustrative location · fictional business': 'Voorbeeldlocatie · fictief bedrijf',
  'Example menu and prices for this fictional business.': 'Voorbeeldmenu en prijzen voor dit fictieve bedrijf.',
  'Example bakes and prices for this fictional business.': 'Voorbeeldassortiment en prijzen voor dit fictieve bedrijf.',
  'Example room types and amenities for this fictional business.': 'Voorbeeldkamers en voorzieningen voor dit fictieve bedrijf.',
  'Example flowers and prices for this fictional business.': 'Voorbeeldbloemen en prijzen voor dit fictieve bedrijf.',
  'Example services and prices for this fictional business.': 'Voorbeelddiensten en prijzen voor dit fictieve bedrijf.',
  'A fictional concept by noordclick.': 'Een fictief concept van noordclick.',
  'Make this yours ↗': 'Maak dit jouw website ↗',
  'The menu': 'De menukaart',
  'Our table': 'Onze tafel',
  'Find us': 'Vind ons',
  'A LITTLE SLOWER.<br>A LITTLE CLOSER.': 'IETS LANGZAMER.<br>IETS DICHTERBIJ.',
  'YOUR NEIGHBOURHOOD TABLE': 'EEN TAFEL IN JE BUURT',
  'Discover tonight’s menu <span aria-hidden="true">↓</span>': 'Ontdek het menu van vanavond <span aria-hidden="true">↓</span>',
  'At the table.': 'Aan tafel.',
  'GOOD FOOD. GOOD COMPANY.': 'LEKKER ETEN. GOED GEZELSCHAP.',
  'The door is open.': 'De deur staat open.',
  'BAKERY. COFFEE. GOOD MORNINGS.': 'BAKKERIJ. KOFFIE. GOEDE MORGENS.',
  'The good stuff': 'Al het lekkers',
  'Our story': 'Ons verhaal',
  'Come by ↗': 'Kom langs ↗',
  'See what’s baking <span aria-hidden="true">↘</span>': 'Kijk wat er in de oven zit <span aria-hidden="true">↘</span>',
  'FRESH.<br>EVERY DAY.': 'VERS.<br>ELKE DAG.',
  'SLOW DOUGH': 'DEEG MET GEDULD',
  'PROPER COFFEE': 'GOEDE KOFFIE',
  'JUST ONE MORE': 'NOG EENTJE DAN',
  'THE COUNTER': 'DE TOONBANK',
  'The good<br>stuff.': 'Al het<br>lekkers.',
  'BAKED TODAY / ENJOY RIGHT AWAY': 'VANDAAG GEBAKKEN / METEEN GENIETEN',
  'THANK YOU. COME HUNGRY.': 'DANK JE WEL. KOM MET TREK.',
  'Come by.': 'Kom langs.',
  'Visit the bakery': 'Bezoek de bakkerij',
  'A SMALL CITY STAY': 'EEN KLEIN VERBLIJF IN DE STAD',
  'Book a stay': 'Boek een verblijf',
  'The rooms': 'De kamers',
  'Our philosophy': 'Onze filosofie',
  'Plan your stay': 'Plan je verblijf',
  '01 — ARRIVAL': '01 — AANKOMST',
  'Find your room <span aria-hidden="true">↗</span>': 'Vind je kamer <span aria-hidden="true">↗</span>',
  '02 — A WAY OF STAYING': '02 — EEN MANIER VAN VERBLIJVEN',
  '03 — THE ROOMS': '03 — DE KAMERS',
  'Make yourself at home.': 'Voel je thuis.',
  'Choose a room': 'Kies een kamer',
  'Enquire about this room': 'Vraag naar deze kamer',
  '04 — THE SMALL DETAILS': '04 — DE KLEINE DETAILS',
  'A soft landing.': 'Rustig aankomen.',
  'Arrival &amp; departure': 'Aankomst &amp; vertrek',
  'Arrival & departure': 'Aankomst & vertrek',
  'the flowers': 'de bloemen',
  'a little about us': 'iets over ons',
  'say hello ↗': 'zeg hallo ↗',
  'gathered with a little love.': 'met liefde bij elkaar gezocht.',
  'Find your flowers <span aria-hidden="true">↘</span>': 'Vind jouw bloemen <span aria-hidden="true">↘</span>',
  'FIELD NOTES / THE COLLECTION': 'VELDNOTITIES / DE COLLECTIE',
  'For someone.<br>For no reason.': 'Voor iemand.<br>Zomaar.',
  'Ask about these ↗': 'Vraag ernaar ↗',
  'A NOTE FROM THE STUDIO': 'EEN BERICHT UIT HET ATELIER',
  'COME AS YOU ARE': 'KOM ZOALS JE BENT',
  'Let’s make<br>someone’s day.': 'Maak iemands<br>dag mooier.',
  'The studio': 'Het atelier',
  'When we’re here': 'Wanneer we er zijn',
  '[ Services ]': '[ Diensten ]',
  '[ The workshop ]': '[ De werkplaats ]',
  '[ Find us ↗ ]': '[ Vind ons ↗ ]',
  'Book a repair ↗': 'Plan een reparatie ↗',
  'AMSTERDAM / BICYCLE CARE': 'AMSTERDAM / FIETSONDERHOUD',
  'What needs fixing?': 'Wat moet er gemaakt worden?',
  '01 / SERVICE BOARD': '01 / DIENSTENBORD',
  'Ask about this service ↗': 'Vraag naar deze dienst ↗',
  '02 / THE WORKSHOP': '02 / DE WERKPLAATS',
  'FIX.<br>RIDE.<br>REPEAT.': 'MAAK.<br>RIJD.<br>HERHAAL.',
  '03 / DROP BY': '03 / KOM LANGS',
  'Bring your bike.': 'Neem je fiets mee.',
  'WORKSHOP HOURS': 'OPENINGSTIJDEN',
  'LOCATION': 'LOCATIE',
  'Get in touch ↗': 'Neem contact op ↗',
  '← Back to noordclick': '← Terug naar noordclick',
  'Choose this design ↗': 'Kies dit ontwerp ↗',
  'Close demo message': 'Demobericht sluiten',
  'noordclick / DESIGN PREVIEW': 'noordclick / ONTWERPVOORBEELD',
  'Picture your business here.': 'Stel je jouw bedrijf hier voor.'
});
